- hosts: web
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: Make sure a service is running
    systemd:
      state: started
      name: httpd
      
    