- name: Install Apache
  package:
    name: apache2
    state: latest
  notify: Restart apache2

- name: Copy Template
  copy:
    src: grandcoffee.zip
    dest: /tmp/

- name: Copy Apache config
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: Restart apache2


